language: python
sudo: enabled
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- nightly
- pypy
- pypy3
env:
  global:
  - CODECOV_TOKEN="9aa6e947-57e8-4546-9f0f-d62f462d4ef7"
  - picbed_redis_url="redis://@localhost"
  jobs:
  - FLASK_VERSION=0.9
  - FLASK_VERSION=0.10
  - FLASK_VERSION=0.11
  - FLASK_VERSION=0.12
  - FLASK_VERSION=1.0
  - FLASK_VERSION=1.1.0
jobs:
  exclude:
  - python: '3.5'
    env: FLASK_VERSION=0.9
  - python: '3.6'
    env: FLASK_VERSION=0.9
  - python: '3.7'
    env: FLASK_VERSION=0.9
  - python: pypy3
    env: FLASK_VERSION=0.9
  - python: pypy3
    env: FLASK_VERSION=0.11
  allow_failures:
  - python: 2.7
  - python: 3.5
  - python: nightly
services:
- redis
install:
- pip install -U -r requirements.txt
- pip install Flask==$FLASK_VERSION
- pip install codecov
script:
- cd src && coverage run -m unittest discover -p "test_*.py"
after_success:
- codecov
